### PR TITLE
feat(): add ci commit type

### PR DESCRIPTION
**Pull request by elilabes**
Commitizen has `ci` as one of the default options. It'd be great to be able to use this tool and have it support all of the options of commitizen.

### CODE REVIEW

**Review by Frikki — APPROVED** [review]

**Comment by Frikki** [comment]
Thanks for your PR.

**Comment by elilabes** [comment]
Thanks @Frikki! Is there any chance this change could be published to NPM? 😄

**Comment by Frikki** [comment]
Ah, yes. I’ll publish a new version.

**Comment by Frikki** [comment]
3.2.0 published!

**Pull request merged**
